services:
  wp-develop:
    image: nginx:alpine

    networks:
      - wpdevnet

    environment:
      LOCAL_DIR: ${LOCAL_DIR-src}

    volumes:
      - ./tools/local-env/default.template:/etc/nginx/conf.d/default.template
      - ./tools/local-env/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www

    command: /bin/sh -c "exec nginx -g 'daemon off;'"

    depends_on:
      wp-php:
        condition: service_started
      wp-db:
        condition: service_healthy

  wp-php:
    image: wordpressdevelop/php:8.4-fpm

    networks:
      - wpdevnet

    environment:
      LOCAL_PHP_XDEBUG: ${LOCAL_PHP_XDEBUG-false}
      XDEBUG_MODE: ${LOCAL_PHP_XDEBUG_MODE-develop,debug}
      LOCAL_PHP_MEMCACHED: ${LOCAL_PHP_MEMCACHED-false}
      PHP_FPM_UID: ${PHP_FPM_UID-1000}
      PHP_FPM_GID: ${PHP_FPM_GID-1000}
      GITHUB_REF: ${GITHUB_REF-false}
      GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME-false}
      HOST_PATH: ${PWD-}/${LOCAL_DIR-src}

    volumes:
      - ./tools/local-env/php-config.ini:/usr/local/etc/php/conf.d/php-config.ini
      - ./:/var/www

    command: /bin/sh -c "if [ $LOCAL_PHP_MEMCACHED = true ]; then cp -n /var/www/tests/phpunit/includes/object-cache.php /var/www/src/wp-content/object-cache.php; else rm -f /var/www/src/wp-content/object-cache.php; fi && exec php-fpm"

    init: true

    extra_hosts:
      - localhost:host-gateway

  wp-db:
    image: mariadb:10

    networks:
      - wpdevnet

    environment:
      MYSQL_ROOT_PASSWORD: password

    volumes:
      - ./tools/local-env/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
      - mysql:/var/lib/mysql

    command: ${LOCAL_DB_AUTH_OPTION-}

    healthcheck:
      test: [
        'CMD-SHELL',
        'mariadb-admin ping -h localhost || exit $$?'
      ]
      timeout: 5s
      interval: 5s
      retries: 10

  wp-cli:
    image: wordpressdevelop/cli:8.4-fpm

    networks:
      - wpdevnet

    environment:
      LOCAL_PHP_XDEBUG: ${LOCAL_PHP_XDEBUG-false}
      LOCAL_PHP_MEMCACHED: ${LOCAL_PHP_MEMCACHED-false}
      PHP_FPM_UID: ${PHP_FPM_UID-1000}
      PHP_FPM_GID: ${PHP_FPM_GID-1000}
      HOST_PATH: ${PWD-}/${LOCAL_DIR-src}

    volumes:
      - ./:/var/www

    init: true

    extra_hosts:
      - localhost:host-gateway

    depends_on:
      wp-php:
        condition: service_started
      wp-db:
        condition: service_healthy

  wp-memcached:
    image: memcached

    networks:
      - wpdevnet

    depends_on:
      wp-php:
        condition: service_started

volumes:
  mysql: {}

networks:
  wpdevnet:
    driver: bridge
