<?php
/**
 * This file was generated by JetBrains Junie
 */

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\CodeQuality\Rector\If_\SimplifyIfReturnBoolRector;
use WigglePuppy\Rector\Rebranding\WordPressToWigglePuppyStringRector;
use WigglePuppy\Rector\Rebranding\WordPressToWigglePuppyCommentRector;

return function (RectorConfig $rectorConfig): void {
    // Define paths to refactor
    $rectorConfig->paths([
        __DIR__ . '/src'
    ]);

    // Skip certain paths
    $rectorConfig->skip([
        __DIR__ . '/src/wp-includes/ID3',
        __DIR__ . '/src/wp-includes/IXR',
        __DIR__ . '/src/wp-includes/PHPMailer',
        __DIR__ . '/src/wp-includes/Requests',
        __DIR__ . '/src/wp-includes/SimplePie',
        __DIR__ . '/src/wp-includes/sodium_compat',
        __DIR__ . '/src/wp-includes/Text',
        // Files specified in rebrand-ignore.txt
        __DIR__ . '/Gruntfile.js',
        __DIR__ . '/package-lock.json',
        // Add other third-party libraries to skip
    ]);

    // Register autoloader for custom rules
    $rectorConfig->autoloadPaths([
        __DIR__ . '/tools/rebranding/rector/src'
    ]);

    // Apply rules
    $rectorConfig->rules([
        // Code Quality Improvements
        SimplifyIfReturnBoolRector::class,

        // WordPress to WigglePuppy Rebranding Rules
        WordPressToWigglePuppyStringRector::class,
        WordPressToWigglePuppyCommentRector::class,
    ]);
};
