<?php
/**
 * This file was generated by Jetbrains Junie
 */

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\CodeQuality\Rector\If_\SimplifyIfReturnBoolRector;

return function (RectorConfig $rectorConfig): void {
    // Define paths to refactor
    $rectorConfig->paths([
        __DIR__ . '/src'
    ]);

    // Skip certain paths
    $rectorConfig->skip([
        __DIR__ . '/src/wp-includes/ID3',
        __DIR__ . '/src/wp-includes/IXR',
        __DIR__ . '/src/wp-includes/PHPMailer',
        __DIR__ . '/src/wp-includes/Requests',
        __DIR__ . '/src/wp-includes/SimplePie',
        __DIR__ . '/src/wp-includes/sodium_compat',
        __DIR__ . '/src/wp-includes/Text',
        // Add other third-party libraries to skip
    ]);

    // Apply only low risk rules
    $rectorConfig->rules([
        // Code Quality Improvements
        SimplifyIfReturnBoolRector::class,
    ]);
};
